//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FVCP.Persistence.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropertyTag
    {
        public int Id { get; set; }
        public string Pin { get; set; }
        public string Name { get; set; }
    
        public virtual Property Property { get; set; }
    }
}
