//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FVCP.Persistence.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Property
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Property()
        {
            this.PropertyTags = new HashSet<PropertyTag>();
        }
    
        public string Pin { get; set; }
        public short ClassNum { get; set; }
        public int TownNum { get; set; }
        public Nullable<short> Volume { get; set; }
        public string LocationId { get; set; }
        public int TaxCode { get; set; }
        public int NeighborhoodId { get; set; }
        public Nullable<short> HomeImpYear { get; set; }
        public string ResType { get; set; }
        public string BuildingUse { get; set; }
        public string AptCount { get; set; }
        public string CommUnits { get; set; }
        public string ExtDesc { get; set; }
        public Nullable<byte> FullBath { get; set; }
        public Nullable<byte> HalfBath { get; set; }
        public string BasementDesc { get; set; }
        public string AtticDesc { get; set; }
        public Nullable<byte> AirCond { get; set; }
        public Nullable<byte> Fireplace { get; set; }
        public string GarageDesc { get; set; }
        public short Age { get; set; }
        public Nullable<int> BuildingSF { get; set; }
        public Nullable<int> LandSF { get; set; }
        public string TotalAllBuildingSF { get; set; }
        public string UnitsTotal { get; set; }
        public string SaleDate { get; set; }
        public Nullable<int> SaleAmount { get; set; }
    
        public virtual PropertyClass PropertyClass { get; set; }
        public virtual Township Township { get; set; }
        public virtual PropertyAddress PropertyAddress { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PropertyTag> PropertyTags { get; set; }
    }
}
