//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FVCP.Persistence.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropertyAddress
    {
        public string Pin { get; set; }
        public string HouseNum { get; set; }
        public string StreetDir { get; set; }
        public string Street { get; set; }
        public string Suffix { get; set; }
        public string Apt { get; set; }
        public string City { get; set; }
        public Nullable<short> Zip { get; set; }
    
        public virtual Property Property { get; set; }
    }
}
